name: magazinedemo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # hooks_riverpod
  # Version：2.3.6
  # License：MIT
  hooks_riverpod: ^2.3.6
#  # flutter_hooks
#  # Version：0.18.6
#  # License：MIT
#  flutter_hooks: ^0.18.6
  # carousel_slider
  # Version：4.2.1
  # License：MIT
  carousel_slider: ^4.2.1
  loop_page_view: ^1.2.5
  infinity_page_view_astro: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

